creation_rules:
  - path_regex: secrets\.yaml
    age:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA156kuescaF7nCQo/2uPK270NlcycypQeSHKbABVuSH mbp
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID36DGwqiYct5AlWNVwB8R5TZWPmsVJm24MTYJ4HozwZ mbp-tuan
