esphome:
  name: ct30w-0
  friendly_name: ct30w-0

web_server:
  port: 80
  version: 3

esp8266:
  board: esp_wroom_02

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret ct30w_0_api_key

ota:
  - platform: esphome
    password: !secret ct30w_0_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  domain: ".lan"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "CT30W-0 Fallback Hotspot"
    password: !secret ct30w_0_fallback_password

captive_portal:

status_led:
  pin: 15

remote_transmitter:
  id: ir_sender
  pin: GPIO14
  carrier_duty_percent: 50%

remote_receiver:
  pin: GPIO5
  dump: all
# climate:
#   - platform: midea_ir
#     name: "AC"
