esphome:
  name: hw-364a
  friendly_name: hw-364a

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret hw_364a_api_key

ota:
  - platform: esphome
    password: !secret hw_364a_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HW-364A Fallback Hotspot"
    password: !secret hw_364a_fallback_password

captive_portal:

i2c:
  sda: GPIO14
  scl: GPIO12
  scan: true # Enable to detect I2C devices
  frequency: 400kHz

font:
  - file: "fusion-pixel-8px-proportional-zh_hans.ttf"
    id: font8
    size: 8
    glyphsets:
      - GF_Latin_Kernel
    glyphs: 你好世界

# OLED Display Configuration
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128X64" # Adjust if your display has a different resolution
    address: 0x3C
    id: hw364a_display
    lambda: |-
      it.printf(64, -2, id(font8), TextAlign::TOP_CENTER, "Hello World! 你好世界");
      it.printf(64, 5, id(font8), TextAlign::TOP_CENTER, "世界 haha 你好");

      it.line(0, 0, 128, 64);
      it.line(0, 64, 128, 0);

      it.line(0, 15, 128, 15 );
      it.line(0, 16, 128, 16 );
