esphome:
  name: s3-lcd
  friendly_name: s3-lcd

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret s3_lcd_api_key

ota:
  - platform: esphome
    password: !secret s3_lcd_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "S3-LCD Fallback Hotspot"
    password: !secret s3_lcd_fallback_password

web_server:
  port: 80
  version: 3

captive_portal:

bluetooth_proxy:

sensor:
  - platform: homeassistant
    id: outdoor_temp
    entity_id: sensor.chaoyang_olympic_sports_center_beijing_zhao_yang_ao_ti_zhong_xin_temperature
    internal: true
    on_value:
      - lvgl.widget.refresh: outdoor_temp_value

  - platform: homeassistant
    id: living_temp
    entity_id: sensor.temperature_humidity_sensor_38ce_temperature
    internal: true
    on_value:
      - lvgl.widget.refresh: living_temp_value

  - platform: homeassistant
    id: bedroom_temp
    entity_id: sensor.temperature_humidity_sensor_aaf6_temperature
    internal: true
    on_value:
      - lvgl.widget.refresh: bedroom_temp_value

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "Boot Button"
    filters:
      - delayed_on_off: 10ms

output:
  - platform: ledc
    pin: GPIO48
    id: backlight

light:
  - platform: esp32_rmt_led_strip
    rgb_order: RGB
    pin: GPIO38
    num_leds: 1
    chipset: ws2812
    name: "Onboard LED"
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: monochromatic
    output: backlight
    name: "Backlight"
    restore_mode: RESTORE_DEFAULT_ON
    initial_state:
      state: True
      brightness: 50%

psram:
  mode: octal
  speed: 80MHZ

text:
  - platform: lvgl
    mode: TEXT
    widget: lbl_id
    name: "Field"

text_sensor:
  - platform: homeassistant
    id: media_state
    entity_id: media_player.xiao_lan
    internal: true
    on_value:
      - if:
          condition:
            lambda: |-
              return id(media_state).has_state() && id(media_state).state == "playing";
          then:
            - lvgl.widget.show: media_container
          else:
            - lvgl.widget.hide: media_container
  - platform: homeassistant
    id: media_title
    entity_id: media_player.xiao_lan
    attribute: media_title
    internal: true
    on_value:
      - lvgl.widget.refresh: media_title_label
  - platform: homeassistant
    id: media_artist
    entity_id: media_player.xiao_lan
    attribute: media_artist
    internal: true
    on_value:
      - lvgl.widget.refresh: media_artist_label

lvgl:
  widgets:
    # - image:
    #     src: album_art_image
    #     id: img_id
    #     image_recolor: 0xFFFFFF
    #     image_recolor_opa: 75%
    - label:
        align: CENTER
        id: lbl_id
        recolor: true
        text: "#FF0000 write# #00FF00 colored# #0000FF text#"
    # Temperature displays
    - label:
        id: outdoor_temp_name
        align: TOP_LEFT
        x: 10
        y: 10
        text: "Outdoor"
    - label:
        id: outdoor_temp_value
        align: TOP_RIGHT
        x: -10
        y: 10
        text: !lambda |-
          if (id(outdoor_temp).has_state()) {
            char buffer[10];
            snprintf(buffer, sizeof(buffer), "%.1f°C", id(outdoor_temp).state);
            return std::string(buffer);
          } else {
            return "--°C";
          }
    - label:
        id: living_temp_name
        align: TOP_LEFT
        x: 10
        y: 30
        text: "Living"
    - label:
        id: living_temp_value
        align: TOP_RIGHT
        x: -10
        y: 30
        text: !lambda |-
          if (id(living_temp).has_state()) {
            char buffer[10];
            snprintf(buffer, sizeof(buffer), "%.1f°C", id(living_temp).state);
            return std::string(buffer);
          } else {
            return "--°C";
          }
    - label:
        id: bedroom_temp_name
        align: TOP_LEFT
        x: 10
        y: 50
        text: "Bed"
    - label:
        id: bedroom_temp_value
        align: TOP_RIGHT
        x: -10
        y: 50
        text: !lambda |-
          if (id(bedroom_temp).has_state()) {
            char buffer[10];
            snprintf(buffer, sizeof(buffer), "%.1f°C", id(bedroom_temp).state);
            return std::string(buffer);
          } else {
            return "--°C";
          }
    # Media information container
    - obj:
        id: media_container
        height: 60
        width: 172
        align: BOTTOM_LEFT
        x: 0
        y: 0
        pad_all: 10
        border_width: 0
        bg_opa: TRANSP
        hidden: true
        scrollbar_mode: "OFF"
        widgets:
          - label:
              id: media_title_label
              align: BOTTOM_LEFT
              x: 0
              y: -20
              text: !lambda |-
                if (id(media_title).has_state()) {
                  return id(media_title).state;
                } else {
                  return "Title: --";
                }
          - label:
              id: media_artist_label
              align: BOTTOM_RIGHT
              x: 0
              y: 0
              text: !lambda |-
                if (id(media_artist).has_state()) {
                  return id(media_artist).state;
                } else {
                  return "Artist: --";
                }
          # - label:
          #     id: media_album_label
          #     align: TOP_LEFT
          #     x: 0
          #     y: 40
          #     text: !lambda |-
          #       if (id(media_album_name).has_state()) {
          #         return "Album: " + id(media_album_name).state;
          #       } else {
          #         return "Album: --";
          #       }
    - obj: # clock container
        height: SIZE_CONTENT
        width: 172
        align: CENTER
        pad_all: 0
        border_width: 0
        # bg_color: 0xFFFFFF
        bg_opa: TRANSP
        scrollbar_mode: "OFF"
        widgets:
          - meter: # clock face
              height: 208
              width: 208
              align: CENTER
              bg_opa: TRANSP
              border_width: 0
              text_color: 0x000000
              scales:
                - range_from: 0 # minutes scale
                  range_to: 60
                  angle_range: 360
                  rotation: 270
                  ticks:
                    width: 1
                    count: 61
                    length: 10
                    color: 0x000000
                  indicators:
                    - line:
                        id: minute_hand
                        width: 3
                        color: 0xa6a6a6
                        r_mod: -4
                        value: 0
                - range_from: 1 # hours scale for labels
                  range_to: 12
                  angle_range: 330
                  rotation: 300
                  ticks:
                    width: 1
                    count: 12
                    length: 1
                    major:
                      stride: 1
                      width: 4
                      length: 10
                      color: 0xC0C0C0
                      label_gap: 12
                - range_from: 0 # hi-res hours scale for hand
                  range_to: 720
                  angle_range: 360
                  rotation: 270
                  ticks:
                    count: 0
                  indicators:
                    - line:
                        id: hour_hand
                        width: 5
                        color: 0xa6a6a6
                        r_mod: -30
                        value: 0
          - label:
              id: day_label
              align: CENTER
              y: -30
          - label:
              id: date_label
              align: CENTER
              y: 30

# Example configuration entry
time:
  - platform: sntp
    # platform: homeassistant
    timezone: Asia/Hong_Kong
    servers:
      - 192.168.88.254
    #  - 0.pool.ntp.org
    #  - 1.pool.ntp.org
    #  - 2.pool.ntp.org
    id: time_comp
    on_time_sync:
      - script.execute: time_update
    on_time:
      - minutes: "*"
        seconds: 0
        then:
          - script.execute: time_update

script:
  - id: time_update
    then:
      - lvgl.indicator.update:
          id: minute_hand
          value: !lambda |-
            return id(time_comp).now().minute;
      - lvgl.indicator.update:
          id: hour_hand
          value: !lambda |-
            auto now = id(time_comp).now();
            return std::fmod(now.hour, 12) * 60 + now.minute;
      - lvgl.label.update:
          id: date_label
          text: !lambda |-
            static const char * const mon_names[] = {"JAN", "FEB", "MAR", "APR", "MAY", "JUN",
                                                     "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"};
            static char date_buf[8];
            auto now = id(time_comp).now();
            snprintf(date_buf, sizeof(date_buf), "%s %2d", mon_names[now.month-1], now.day_of_month);
            return date_buf;
      - lvgl.label.update:
          id: day_label
          text: !lambda |-
            static const char * const day_names[] = {"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};
            return day_names[id(time_comp).now().day_of_week - 1];

spi:
  clk_pin: GPIO40
  mosi_pin: GPIO45

display:
  - platform: st7789v
    model: WAVESHARE_1.47IN_172X320
    dc_pin: GPIO41
    reset_pin: GPIO39
    cs_pin: GPIO42
    # backlight_pin: GPIO48
    rotation: 0
